### ISSUE TITLE
Explain parameters

### ISSUE THREAD

**Issue by Karol-G** [jviquerat/bezier_shapes#2]
Hey,

cool project! But could you maybe document what the parameters do?

For example the parameters in generate_dataset?

magnify        = 1.0
xmin           =-2.0
xmax           = 2.0
ymin           =-2.0
ymax           = 2.0
n_tri_max      = 5000

**Comment by jviquerat** [comment]
Hi,

Thanks for the appreciation.
- The (```xmin```, ```xmax```, ...) control the size of the domain around the shape. So if you chose ```[-1,1]x[-1,1]```, you shape will be drawn in a square of lateral size 1. It also controls the size of the meshed domain in the case where ```mesh_domain``` is set to ```True```.
- ```magnify``` applies an homothetic transformation of the shape with respect to its center (i.e. the center of mass of its control points)
- ```n_tri_max``` sets a maximal acceptable size for the produced mesh, above which the ```generated``` marker is set to False, and the current shape is dropped. This is a useful control parameter in the case where you will perform numerical computation on the produced mesh (my case). If you don't care, you can just set it to a very high value (1.000.000 for example)

**Comment by Karol-G** [comment]
Thanks for the explanation!
